sudo: false
language: node_js
node_js:
  - "5"
  - "6"
addons:
  code_climate: true
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install
script:
  - npm run coverage
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
